version: "3.4"

services:
  backend:
    image: instigpt-backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    networks:
      - net
    depends_on:
      - vector_db
      - relational_db

  vector_db:
    image: chromadb/chroma:latest
    restart: unless-stopped
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    volumes:
      - ./embeddings:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - net

  relational_db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - net

  frontend:
    image: instigpt-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - net

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net

networks:
  net:
    driver: bridge
